# Generated by Django 2.0.7 on 2018-09-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
