# Generated by Django 2.0.7 on 2018-09-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20180919_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=500)),
                ('option1', models.CharField(blank=True, max_length=500, null=True)),
                ('option2', models.CharField(blank=True, max_length=500, null=True)),
                ('option3', models.CharField(blank=True, max_length=500, null=True)),
                ('option4', models.CharField(blank=True, max_length=500, null=True)),
                ('option5', models.CharField(blank=True, max_length=500, null=True)),
                ('ans', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='quiz_team',
            name='allquestions',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='questionnaire.Question'),
        ),
    ]
