# Generated by Django 2.0.7 on 2018-09-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_ans_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_team',
            name='allquestions',
            field=models.ManyToManyField(blank=True, default=None, to='questionnaire.Question'),
        ),
    ]
