# Generated by Django 2.0.7 on 2018-09-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20180921_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_team',
            name='allanswers',
            field=models.ManyToManyField(blank=True, default=None, to='questionnaire.Ans_chosen'),
        ),
    ]
