# Generated by Django 2.0.7 on 2018-09-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_remove_question_option5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',)},
        ),
    ]
