# Generated by Django 2.0.7 on 2018-09-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20180923_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_team',
            name='quiz_submitted',
            field=models.BooleanField(default=True),
        ),
    ]
