# Generated by Django 2.0.7 on 2018-09-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_quiz_team_quiz_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_team',
            name='quiz_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
