# Generated by Django 2.0.7 on 2018-09-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_auto_20180923_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_team',
            name='quiz_submitted',
        ),
        migrations.AddField(
            model_name='quiz_team',
            name='not_submitted',
            field=models.BooleanField(default=True),
        ),
    ]
