# Generated by Django 2.0.7 on 2018-08-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180820_1816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventDetail',
            new_name='Detail',
        ),
    ]
