# Generated by Django 2.0.7 on 2018-09-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180821_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.CharField(default='#', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='pslink',
            field=models.CharField(default='#', max_length=200),
            preserve_default=False,
        ),
    ]
