# Generated by Django 2.0.7 on 2018-09-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20180915_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_workshop',
            field=models.BooleanField(default=False),
        ),
    ]
