# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_auto_20180617_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
