# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0003_auto_20180621_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='name',
            field=models.TextField(),
        ),
    ]
