# Generated by Django 2.0.5 on 2018-07-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0005_auto_20180709_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ca',
            old_name='mobile',
            new_name='phone',
        ),
    ]
