# Generated by Django 2.0.7 on 2018-07-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0007_auto_20180709_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ca',
            options={'ordering': ('-points',)},
        ),
        migrations.AddField(
            model_name='ca',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
