# Generated by Django 2.0.7 on 2018-07-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0008_auto_20180717_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
    ]
