# Generated by Django 2.0.7 on 2018-07-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0009_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
