# Generated by Django 2.0.7 on 2018-07-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0012_auto_20180717_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postMessage',
            new_name='Message',
        ),
    ]
