# Generated by Django 2.0.5 on 2018-09-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0014_auto_20180909_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
