# Generated by Django 2.0.5 on 2018-09-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0015_auto_20180909_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
