# Generated by Django 2.0.7 on 2018-09-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profiles_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='shilpid',
            field=models.CharField(default='SH10032', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiles',
            name='accomodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='delta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='enviro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='icreate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='mudmarine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='nirman',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='paper_presentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='questionnaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='this_or_that_way',
            field=models.BooleanField(default=False),
        ),
    ]
