# Generated by Django 2.0.7 on 2018-09-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180902_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='payment_plan',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
