# Generated by Django 2.0.7 on 2018-09-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180902_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='paper_presentation',
            new_name='paper',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='team_paper_presentation',
            new_name='team_paper',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='team_this_or_that_way',
            new_name='team_thisway',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='this_or_that_way',
            new_name='thisway',
        ),
    ]
