# Generated by Django 2.0.7 on 2018-09-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20180902_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='delta',
            new_name='event_delta',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='enviro',
            new_name='event_enviro',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='icreate',
            new_name='event_icreate',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='mudmarine',
            new_name='event_mudmarine',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='nirman',
            new_name='event_nirman',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='paper',
            new_name='event_paper',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='questionnaire',
            new_name='event_questionnaire',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='team_nirman',
            new_name='event_team_nirman',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='thisway',
            new_name='event_thisway',
        ),
    ]
