# Generated by Django 2.0.7 on 2018-09-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_team'),
        ('user', '0012_profiles_events_locked'),
    ]

    operations = [
    ]
