# Generated by Django 2.0.7 on 2018-09-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20180903_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='tshirt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='payment_plan',
            field=models.CharField(max_length=100),
        ),
    ]
