# Generated by Django 2.0.7 on 2018-09-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_profiles_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='event_paper',
            new_name='event_idp',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='event_team_nirman',
            new_name='event_paper_presentation',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='event_thisway',
            new_name='event_this_way_or_that_way',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='team_paper',
            new_name='team_idp',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='team_thisway',
            new_name='team_nirman',
        ),
        migrations.AddField(
            model_name='profiles',
            name='team_paper_presentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profiles',
            name='team_this_way_or_that_way',
            field=models.BooleanField(default=False),
        ),
    ]
