# Generated by Django 2.0.7 on 2018-09-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20180904_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='event_this_way_or_that_way',
            new_name='event_this_way_that_way',
        ),
    ]
