# Generated by Django 2.0.7 on 2018-09-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20180904_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='team_paper_presentation',
            new_name='team_colloquiom',
        ),
    ]
