# Generated by Django 2.1 on 2018-09-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20180905_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='plan_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='num_events',
            field=models.IntegerField(default=0),
        ),
    ]
