# Generated by Django 2.0.7 on 2018-09-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20180906_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='event_colloquiom',
            new_name='event_colloquium',
        ),
    ]
