# Generated by Django 2.0.7 on 2018-09-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20180919_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='txid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
