# Generated by Django 2.0.7 on 2018-09-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_profiles_txid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='college_name',
            field=models.CharField(max_length=200),
        ),
    ]
